# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lewis/repo/File-OS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lewis/repo/File-OS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lewis/repo/File-OS/CMakeFiles /Users/lewis/repo/File-OS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lewis/repo/File-OS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named File-OS

# Build rule for target.
File-OS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 File-OS
.PHONY : File-OS

# fast build rule for target.
File-OS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/build
.PHONY : File-OS/fast

src/DiskMannger.o: src/DiskMannger.cpp.o

.PHONY : src/DiskMannger.o

# target to build an object file
src/DiskMannger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/DiskMannger.cpp.o
.PHONY : src/DiskMannger.cpp.o

src/DiskMannger.i: src/DiskMannger.cpp.i

.PHONY : src/DiskMannger.i

# target to preprocess a source file
src/DiskMannger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/DiskMannger.cpp.i
.PHONY : src/DiskMannger.cpp.i

src/DiskMannger.s: src/DiskMannger.cpp.s

.PHONY : src/DiskMannger.s

# target to generate assembly for a file
src/DiskMannger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/DiskMannger.cpp.s
.PHONY : src/DiskMannger.cpp.s

src/FAT.o: src/FAT.cpp.o

.PHONY : src/FAT.o

# target to build an object file
src/FAT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/FAT.cpp.o
.PHONY : src/FAT.cpp.o

src/FAT.i: src/FAT.cpp.i

.PHONY : src/FAT.i

# target to preprocess a source file
src/FAT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/FAT.cpp.i
.PHONY : src/FAT.cpp.i

src/FAT.s: src/FAT.cpp.s

.PHONY : src/FAT.s

# target to generate assembly for a file
src/FAT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/FAT.cpp.s
.PHONY : src/FAT.cpp.s

src/FCB.o: src/FCB.cpp.o

.PHONY : src/FCB.o

# target to build an object file
src/FCB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/FCB.cpp.o
.PHONY : src/FCB.cpp.o

src/FCB.i: src/FCB.cpp.i

.PHONY : src/FCB.i

# target to preprocess a source file
src/FCB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/FCB.cpp.i
.PHONY : src/FCB.cpp.i

src/FCB.s: src/FCB.cpp.s

.PHONY : src/FCB.s

# target to generate assembly for a file
src/FCB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/FCB.cpp.s
.PHONY : src/FCB.cpp.s

src/File.o: src/File.cpp.o

.PHONY : src/File.o

# target to build an object file
src/File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/File.cpp.o
.PHONY : src/File.cpp.o

src/File.i: src/File.cpp.i

.PHONY : src/File.i

# target to preprocess a source file
src/File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/File.cpp.i
.PHONY : src/File.cpp.i

src/File.s: src/File.cpp.s

.PHONY : src/File.s

# target to generate assembly for a file
src/File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/File.cpp.s
.PHONY : src/File.cpp.s

src/Folder.o: src/Folder.cpp.o

.PHONY : src/Folder.o

# target to build an object file
src/Folder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/Folder.cpp.o
.PHONY : src/Folder.cpp.o

src/Folder.i: src/Folder.cpp.i

.PHONY : src/Folder.i

# target to preprocess a source file
src/Folder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/Folder.cpp.i
.PHONY : src/Folder.cpp.i

src/Folder.s: src/Folder.cpp.s

.PHONY : src/Folder.s

# target to generate assembly for a file
src/Folder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/Folder.cpp.s
.PHONY : src/Folder.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/File-OS.dir/build.make CMakeFiles/File-OS.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... File-OS"
	@echo "... src/DiskMannger.o"
	@echo "... src/DiskMannger.i"
	@echo "... src/DiskMannger.s"
	@echo "... src/FAT.o"
	@echo "... src/FAT.i"
	@echo "... src/FAT.s"
	@echo "... src/FCB.o"
	@echo "... src/FCB.i"
	@echo "... src/FCB.s"
	@echo "... src/File.o"
	@echo "... src/File.i"
	@echo "... src/File.s"
	@echo "... src/Folder.o"
	@echo "... src/Folder.i"
	@echo "... src/Folder.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

